#!/bin/bash

###!/usr/bin/env sh

# Attempt to set SCRIPT_DIR
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' >/dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/$link"
  fi
done

# Check for git
GIT=$(command -v git)
if [ -z $GIT ]; then
  echo "Git executable does not exists"
fi

SAVED="$(pwd)"
cd "$(dirname "$PRG")/" >/dev/null
SCRIPT_DIR="$(pwd -P)"
cd "$SAVED" >/dev/null


# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")"
fi

FLUTTER_SUBMODULE_NAME='.flutter'
FLUTTER_DIR="$SCRIPT_DIR/$FLUTTER_SUBMODULE_NAME"

GIT_REPO="false"

# If not a git repo, it used .flutter but it will not handled as submodule
if git rev-parse --git-dir > /dev/null 2>&1; then
  GIT_REPO="true"
else
  # echo "CHECKING: Not a git repository"
  if test -z "${FLUTTER_HOME-}"; then
    FLUTTER_HOME="$FLUTTER_DIR"
  fi
fi

# When flutter home given that flutter version used, there is no submodule handling
if test -n "${FLUTTER_HOME-}"; then
  # echo "Flutter HOME used: ${FLUTTER_HOME}"
  FLUTTER_DIR="$FLUTTER_HOME"
fi

#The given flutter dir does not exists, checking out
if [ ! -d "${FLUTTER_DIR}" ]; then
  echo "Flutter not found, installing..."
  if [ -z $FLUTTER_CHANNEL ]; then
    FLUTTER_CHANNEL=stable
  fi
  git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL --depth 1 $FLUTTER_DIR
fi

# Flutter home not given, handling as submodule. When git parse does not now as submodule,
# the FLUTTEr_HOME variable set earlier
if test -z "${FLUTTER_HOME-}"; then
  # echo "Checking submodule"
  # submodule starting with "-" are not initialized
  init_status=$(git submodule | grep "\ $FLUTTER_SUBMODULE_NAME$" | cut -c 1)

  # Fix not initialized flutter submodule
  if [ "$init_status" = "-" ]; then
    echo "$FLUTTER_SUBMODULE_NAME submodule not initialized. Initializing..."
    git submodule update --init ${FLUTTER_SUBMODULE_NAME}
  fi
fi

# Detect detach HEAD and fix it. commands like upgrade expect a valid branch, not a detached HEAD
FLUTTER_SYMBOLIC_REF=$(git -C ${FLUTTER_DIR} symbolic-ref -q HEAD)
if [ -z ${FLUTTER_SYMBOLIC_REF} ]; then
  FLUTTER_REV=$(git -C ${FLUTTER_DIR} rev-parse HEAD)
  FLUTTER_CHANNEL=$(git config -f .gitmodules submodule.${FLUTTER_SUBMODULE_NAME}.branch)

  if [ -z $FLUTTER_CHANNEL ]; then
    echo "Warning: Submodule '$FLUTTER_SUBMODULE_NAME' doesn't point to an official Flutter channel \
(one of stable|beta|dev|master). './flutterw upgrade' will fail without a channel."
    echo "Fix this by adding a specific channel with:"
    echo "\t- './flutterw channel <channel>' or"
    echo "\t- Add 'branch = <channel>' to '$FLUTTER_SUBMODULE_NAME' submodule in .gitmodules"
  else
    echo "Fixing detached HEAD: '$FLUTTER_SUBMODULE_NAME' submodule points to a specific commit $FLUTTER_REV, not channel '$FLUTTER_CHANNEL' (as defined in .gitmodules)."
    # Make sure channel is fetched
    # Remove old channel branch because it might be moved to an unrelated commit where fast-forward pull isn't possible
    git -C ${FLUTTER_DIR} branch -q -D ${FLUTTER_CHANNEL} 2> /dev/null || true
    git -C ${FLUTTER_DIR} fetch -q origin

    # bind current HEAD to channel defined in .gitmodules
    git -C ${FLUTTER_DIR} checkout -q -b ${FLUTTER_CHANNEL} ${FLUTTER_REV}
    git -C ${FLUTTER_DIR} branch -q -u origin/${FLUTTER_CHANNEL} ${FLUTTER_CHANNEL}
    echo "Fixed! Migrated to channel '$FLUTTER_CHANNEL' while staying at commit $FLUTTER_REV. './flutterw upgrade' now works without problems!"
    git -C ${FLUTTER_DIR} status -bs
  fi
fi




if test -n ""; then
  if [[ ! -f $SCRIPT_DIR/chromew ]]; then
    base64 -d <<<IyEvYmluL3NoCmlmIFsgImB1bmFtZWAiID0gIkRhcndpbiIgXTsgdGhlbgogIENIUk9NRV9CSU49L0FwcGxpY2F0aW9ucy9Hb29nbGVcIENocm9tZS5hcHAvQ29udGVudHMvTWFjT1MvR29vZ2xlXCBDaHJvbWUKZWxpZiBbICJgdW5hbWVgIiA9ICJMaW51eCIgXTsgdGhlbgogIENIUk9NRV9CSU49JCh3aGljaCBnb29nbGUtY2hyb21lKQplbHNlCiAgZWNobyAiVW5zdXBwb3J0ZWQgT1MiCiAgZXhpdCAxCmZpCgplY2hvICJDaHJvbWU6ICRDSFJPTUVfQklOIgppZiBbICEgLWYgIiR7Q0hST01FX0JJTn0iIF07IHRoZW4KICBlY2hvICJHb29nbGUgY2hyb21lIG5vdCBmb3VuZCIKICBleGl0IDEKZmkKCiNleGUgYyBiYXNoIC1jICJleGVjICR7Q0hST01FX0JJTn0gLS1kaXNhYmxlLXdlYi1zZWN1cml0eSAtLXVzZXItZGF0YS1kaXI9XCIuY2hyb21lXCIgJCoiCgoiJENIUk9NRV9CSU4iIC0tZGlzYWJsZS13ZWItc2VjdXJpdHkgLS11c2VyLWRhdGEtZGlyPSIuY2hyb21lIiAkKg== > $SCRIPT_DIR/chromew
    chmod +x $SCRIPT_DIR/chromew
  fi
  if [[ ! -f $SCRIPT_DIR/Chromew.cmd ]]; then
    base64 -d <<<ImM6XFByb2dyYW0gRmlsZXMgKHg4NilcR29vZ2xlXENocm9tZVxBcHBsaWNhdGlvblxjaHJvbWUuZXhlIiAtLWRpc2FibGUtd2ViLXNlY3VyaXR5IC0tdXNlci1kYXRhLWRpcj0iLmNocm9tZSIgJSo= > $SCRIPT_DIR/Chromew.cmd
  fi
fi
if test -n "${CHROME_CORS_DISABLE-}"; then
  export CHROME_EXECUTABLE="$SCRIPT_DIR/chromew"
fi

# Wrapper tasks done, call flutter binay with all args
set -e
"$FLUTTER_DIR/bin/flutter" "$@"

# Post flutterw tasks. exit code from /bin/flutterw will be used as final exit
FLUTTER_EXIT_STATUS=$?
if [ ${FLUTTER_EXIT_STATUS} -eq 0 ]; then

  if test -n "${FLUTTER_HOME-}"; then

    # ./flutterw channel CHANNEL
    if echo "$@" | grep -q "channel"; then
      # make sure .gitmodules is updated as well
      CHANNEL=${2} # second arg
      git config -f .gitmodules submodule.${FLUTTER_SUBMODULE_NAME}.branch ${CHANNEL}
      # makes sure nobody forgets to do commit all changed files
      git add .gitmodules
      git add ${FLUTTER_SUBMODULE_NAME}
    fi

    # ./flutterw upgrade
    if echo "$@" | grep -q "upgrade"; then
      # makes sure nobody forgets to do commit the changed submodule
      git add ${FLUTTER_SUBMODULE_NAME}
      # flutter packages get runs automatically. Stage those changes as well
      git add pubspec.lock
    fi
  fi
fi
exit ${FLUTTER_EXIT_STATUS}
