name: judo_flutter_components
description: Judo Components module.

version: 1.9.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'
    
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  intl: any
  mobx: any
  flutter_mobx: any

  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.blackbelt.judo_flutter_components
    iosBundleIdentifier: com.blackbelt.judoFlutterComponents
